sudo: false
dist: trusty

language: java

jdk:
- openjdk11

install: true
script: mvn package

after_success: cp target/massim-*.tar.gz massim-${TRAVIS_BRANCH}.tar.gz

deploy:
  provider: releases
  api_key:
    secure: JVCX8vo5I5gTXFM7+cSPlD9NWq9v+NI09hd17glPoHgYLGfA/GQTPzb+x434qXK9wdHv5hI4Wq7DJn3VB4Nvj5B4de8uvz85clZ5luxeSo50CiQSJZZtF+QImwviLub1dDlEYttmWemjhibTVhelXcRWyeGkFmtP/ED5oHyiIv2NP1J6w+PzlT8J1v6wJ74e2id96tjEYlah82MDzo5D10M6kIVEnVbq6FvJG2PBz/2OQtbR6keruuhVHLOocU75rgCULn6yN4qWNNuu+6b4HwBBmM8b/vdZkn3TZYJ7xT2auAfG21kfmxBQgAtcrtl+LynsCycDjdS9P7B1TzwSqIX5q74xrTcdaUYotqWlj+M64CJIpocrord5tCSxUXjkWoNGKNpqYyfksMy5cAy5Z2iFxZZFIRzr5/8x0DJlgnI7GNO+0mN0gutjZdJViz7SEagqpm1HmtvKurch1Q320GTX34p1BlmI4KXzw3SlDPO2So3hIR9sxG4SBR0eTiXJ6cBJD6p4ObkbhYAgMFI/aAHq59bVWdtWkov9lWWpJyN7+/da4fgEoNLEEXNR+Z5r4dNHOv9/8FNKkO4KHKHZ/097iHi8n7OnWH6C5nZrAloMxV0L9c4acXObTQ5J1P9q+TBv2EDRzlYFLls9z+wj8omCeibz1vLRqG+E2gHpsMk=
  file: target/massim-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: agentcontest/massim_2019
    branch: master

addons:
  artifacts:
    bucket: agentcontest
    s3_region: eu-west-1
    paths: $(ls massim-*.tar.gz)
    target_paths: massim
    cache_control: public
    key:
      secure: rk0e1W5Jp4+kkgRNW1N1ka0Yy+R/5f6LVxlJDs1Hdai2K3OWodtipF7f5uppVI3uWdWP6xoacEW7YgapCh+78Jr8jEmEUR7CL+OiTcnkCik/6wLr71pKeQYQkIeiWrorRb1NLkInOdcNCpyZtY42hzT+AKQvONCbn56XV7wEv8YqMRLt6ux0QIuOlHzLP9lR1UCIkAi1CO2T6MNmKeDuRb11JaPfxyWFATaiCS01byRfvBG/mrqZPrp4tSnUMi4XxS1G4il58uwjV9+safTEHEnk4Bz1c4p5ZhUCxmNLnpmgYdUI46PI/ZWHSma9VMYruLZemP2NjWWxINvSHtp1UAGicPvEYPWrXI8QVxv6UJvrynVvfVa/n2bmAA6OKQJ81H9vMIRdTsFJ0ClL8RsYhOEj3Y2BG9JiDNkEIe2OjMfXD7rdPyO7Y7bpiy0tpoazy37LHt6RsjcSYXvM5Ua9psYUhZydpLcmvfAvKxqwEO7y+9egvb55GZww+k5RMC9VDN4vy6QN8insXaYY7vemyLneV2HpN87PtQbnsbFMJyUM3aGSRxLbHNoWvg/CFwHVl6rtbGa9fKSSSZiDTEKVElaHrwECTzNDj+Li2YGMiSmMyVqHbEXZateMnWEvaS5a0HIkSNjSJjvc+bgJTQ+llva2HgqSZ2Xxs4G1NvHDh40=
    secret:
      secure: vBf/FHCWqWHkMra1LohBrlom7Icunxy0eaCZ9c1m/tJqlEMMfoOFeTamle3LZNVS3e6vN+IKIJlec0SAveO9F7BEa4PHmhXQQ+rxwUt50gGFQwQh22Wbgj67CCBXgsud8ZpezH5tjm8O14kZumUcdKS6tFzoyMQZeWC06x4IHiEtWkSpI7SwnATsX4dUG1B33nBzA+pjvUJGMwU+aYdok77iP3TNxBL0GY4lL2rHEusma/gCD8ueszk2RR66AwmPW4VTXAg9PrjKFdQVSmvxvS1Hz2DuXCTnnLf4yBWPnbM8DygzFHfQdz7hQSzlzWoCVxmKz8QgfYhfmf6RGnWhubkFIh8IXXJH8T5IrZLM0hmzrjuDeDC0+C30jzaMoGgOz8spCcyzylXOIoJttzp8CX0r/qspRf/FB7y5SPh6AuYVGqyacdaCErVubT2jMPpCDla12ppQ5NJeELQvXhjk/euU5eC6EqjA+C11mwbS1GxVOwQbAwfWBTz0SLlBTaDGmqYz3B4jltMNPzVujBpkgHXLkf4+UtFncV12gwa54Wi+Wm5vlvB/6JYAMNS79Hwybfc7tk4QgyHibZuwNUrKYEuwi6Xf3gsVkXhLseYVCh3Giya4DgM0eEcqwMe+FFcFwtVkz0mKqJa/ZQEB+39EgKjaz1aye6XKXsMWQI5QWqY=
